sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_ID/multi-docker npm run test -- --coverage

after_success:
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker
  - docker build -t $DOCKER_ID/multi-nginx ./nginx
# Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
  - docker push $DOCKER_ID/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-882053630588
  bucket_path: docker-multi
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master